# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions


alias nfo='cat ~/ICAAPCS/German/*Unit/*Lesson/nfo'
alias ls='\ls' # disable colored output
alias fp='sudo chmod 777 ~/ICA* -R'
alias logind='sudo nano /etc/systemd/logind.conf'
